### PR TITLE
fix: preserve calc when extra parentheses are used

### LINKED ISSUE #181: [Bug]: `calc` disappears if extra pair of parentheses around the argument
### Describe the bug

If you add an extra pair of parentheses around the argument to the `calc` function, `postcss-calc` removes the `calc` token.
For example:
`calc((var(--circumference) / var(--number-of-segments)))`
turns into
`(var(--circumference) / var(--number-of-segments))`

### Expected behaviour

`calc` should stay and the extra parentheses disappear:

 `calc((var(--circumference) / var(--number-of-segments)))`
turns into
`calc(var(--circumference) / var(--number-of-segments))`

### Steps to reproduce

See https://github.com/postcss/postcss-calc/pull/180

### Version

8.2.4

### Environment

```shell
System:
    OS: Linux 6.2 Fedora Linux 38 (Workstation Edition)
    CPU: (16) x64 AMD Ryzen 7 PRO 5850U with Radeon Graphics
    Memory: 27.19 GB / 30.17 GB
    Container: Yes
    Shell: 3.6.1 - /usr/bin/fish
```

### Package details

```shell
postcss-calc@8.2.4 /home/ludovico/projects/scratch/postcss-calc
├─┬ postcss-selector-parser@6.0.9 -> ./node_modules/.pnpm/postcss-selector-parser@6.0.9/node_modules/postcss-selector-parser
│ └── postcss@8.4.5 deduped -> ./node_modules/.pnpm/postcss@8.4.5/node_modules/postcss
└── postcss@8.4.5 -> ./node_modules/.pnpm/postcss@8.4.5/node_modules/postcss
```

### Additional context

Originally submitted on the cssnano repository: https://github.com/cssnano/cssnano/issues/1490

### PR DESCRIPTION
**Pull request by tannerdolby**
Fixes #181

This fix allows `calc` to be printed when `calc((...))` is encountered. The bug occurred because the AST was `'type: 'ParenthesizedExpression'` which didn't satisfy the [`shouldPrintCalc`](https://github.com/postcss/postcss-calc/blob/master/src/lib/stringifier.js#L75) check in `stringifier.js`. The test I added piggy backs on the work started in #180. All the original tests pass with this addition, but I am new to the codebase so I very well could be missing some things.

https://github.com/cssnano/cssnano/issues/1490#issuecomment-1534215112

TODOs:
- remove the extra parentheses e.g. `calc((var(--foo) / var(--bar))` should become `calc(var(--foo) / var(--bar)`
- preserve the space between the division operator e.g. `calc((var(--foo) / var(--bar))` should preserve the space if that is intended/expected behavior.

### CODE REVIEW

File: src/lib/stringifier.js [hunk 1]
```diff
@@ -73,7 +73,8 @@ module.exports = function (calc, node, originalValue, options, result, item) {
   let str = stringify(node, options.precision);
 
   const shouldPrintCalc =
-    node.type === 'MathExpression' || node.type === 'Function';
+    node.type === 'MathExpression' || node.type === 'Function' ||
+    node.type === 'ParenthesizedExpression';
 
   if (shouldPrintCalc) {
     // if calc expression couldn't be resolved to a single value, re-wrap it as
```
Comment (ludofischer) [inline src/lib/stringifier.js:80]: Maybe you can remove the double round brackets by changing line 81-82:
```javascript
if (node.type === 'ParenthesizedExpression') {
 str = `${calc}${str}`;
else {
  str = `${calc}(${str})`;
}

**Comment by ludofischer** [comment]
Good job! I think we're very close to being able to simplify the external parentheses completely. Regarding the second TODO, do you think there's a reason to preserve the space around the division operator?

File: src/lib/stringifier.js (hunk 1 above)
Comment (tannerdolby) [reply src/lib/stringifier.js:80]: Good call, that gets the job done and removes any extra parentheses whether it's one or many. Will update this now.

**Comment by tannerdolby** [comment]
@ludofischer Thank you! After implementing your suggested changes, I think we are close to completely fixing the bug. In regards to the second TODO, I don't think there is any reason to preserve the space around the division operator. Especially because that space isn't preserved in other tests so I think it makes sense to keep things as is.

**Review by ludofischer — APPROVED** [review]
